language: generic
sudo: false
cache:
  timeout: 30 # caching only saves about a minute anyway
  directories:
    - /tmp/autoconf

env:
  global:
    - EMACS_REV=emacs-25.3

install:
  - . travis-steps.sh "$EMACS_REV" "$EMACS_VERSION"
  - download
  - unpack
  - autogen
  - configure
  - curl -Lo "/tmp/${EMACS_REV}.tar.gz" "$url/${EMACS_REV}.tar.gz"
  - tar -xzf /tmp/${EMACS_REV}.tar.gz -C /tmp
  - curl -LO https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  # Configure $PATH: Emacs installed to /tmp/emacs
  - export PATH=/tmp/emacs/bin:${PATH}

script:
  - cd ${srcdir}/test/automated && make EMACS=emacs check


notifications:
  email: never
